# Generated by Django 5.0.1 on 2024-01-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_evaluator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='test_cases',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
