# Generated by Django 5.0.1 on 2024-01-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_evaluator', '0003_rename_evaluation_metrics_exercise_evaluation_metrics_model1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewExercise',
            fields=[
                ('exercise_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('expected_solution', models.TextField()),
                ('generated_solution_model1', models.TextField(blank=True, null=True)),
                ('generated_solution_model2', models.TextField(blank=True, null=True)),
                ('evaluation_metrics_model1', models.JSONField(blank=True, null=True)),
                ('evaluation_metrics_model2', models.JSONField(blank=True, null=True)),
                ('programming_language', models.CharField(max_length=50)),
                ('difficulty_level', models.CharField(max_length=20)),
                ('test_cases', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
