# Generated by Django 5.0.1 on 2024-01-29 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_evaluator', '0004_newexercise'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
